
name: Run Test cases

on: 
  pull_request: 
    # branches: [testing]
  
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Build Docker image
          run: |
            docker build -t ai_chat_bot:latest
        - name: Build and tag docker image
          run: |
            docker buildx build --platform linux/amd64 \
            --tag ai_chat_bot:latest \
            -f Dockerfile.ci \ 
            --load \
            .
        - name: Check if image was built
          run: | 
            docker images ai_chat_bot:latest
            
        - name: Output Result 
          run: echo "Image Built"
        
        - name: Create coverage directory
          run: |
            mkdir -p ./coverage
            
        - name: Install lcov
          run: sudo apt-get install lcov
        - name: Copy coverage report from container
          run: |
            docker create --name bot-container AI_CHAT_BOT:latest
            docker cp bot-container:/app/jacoco.xml ./coverage/
            docker rm bot-container
        - name: Convert JaCoco to LCOV
          run: |
            bash <curl -s https://codecov.io/bash) -f ./coverage/jacoco.xml -o ./coverage/lcov.info
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage/jacoco.xml,./coverage/lcov.info
            flags: unittests
            name: codecov-umbrella
            fail_ci_if_error: true
